packages:
- wolf-api
- wolf-cli
- wolf-client
- wolf-cub
- wolf-data
- wolf-data-baked
- wolf-email
- wolf-google
- wolf-mutt
- wolf-server
- wolf-test-utils
- wolf-web-server

extra-deps:
- servant-quickcheck-0.0.2.4
- sockaddr-0.0.0
- wai-git-http-0.0.0
- git: https://github.com/NorfairKing/typed-uuid.git
  commit: a7baf4999c901ccdeb66dba0221431de692963f1
  subdirs:
    - typed-uuid
    - genvalidity-typed-uuid
- mime-0.4.0.2
- git: https://github.com/mkawalec/emailparse
  commit: 39987dc1c2159b0660521824323e1f3974a233f0
- either-4.4.1.1
- strptime-1.0.10
resolver: lts-10.2
