name: wolf-data
version: '0.0.0.0'
category: People
author: Tom Sydney Kerckhove
maintainer: syd.kerckhove@gmail.com
copyright: ! 'Copyright: (c) 2017 Tom Sydney Kerckhove'
license: AllRightsReserved
homepage: http://cs-syd.eu
default-extensions:
- NoImplicitPrelude
dependencies:
- base >=4.9
- aeson >=1.0
- aeson-pretty >=0.8
- bytestring >=0.10
- cautious >=0.3
- conduit >=1.2
- containers >=0.5
- deepseq >=1.4
- exceptions >=0.8
- filepath >=1.4
- hashable >=1.2
- hashable-time >=0.2
- mtl >=2.2
- path >=0.6
- path-io >=1.3
- process >=1.6
- resourcet >=1.1
- servant-server >=0.9
- text >=1.2
- time >=1.8
- typed-uuid >=0.0
- unordered-containers >=0.2
- uuid >=1.3
- validity >=0.4
- validity-aeson >=0.1
- validity-containers >=0.2
- validity-path >=0.2
- validity-text >=0.2
- validity-time >=0.1
- validity-uuid >=0.0
- yaml >=0.8
library:
  source-dirs: src/
  ghc-options: -Wall
  exposed-modules:
  - Wolf.Data
  - Wolf.Data.Cautious
  - Wolf.Data.Entry
  - Wolf.Data.Entry.Types
  - Wolf.Data.Export
  - Wolf.Data.Export.Types
  - Wolf.Data.Cleanup
  - Wolf.Data.Git
  - Wolf.Data.Import
  - Wolf.Data.Import.Types
  - Wolf.Data.Index
  - Wolf.Data.Index.Types
  - Wolf.Data.Init
  - Wolf.Data.Init.Types
  - Wolf.Data.JSONUtils
  - Wolf.Data.Note
  - Wolf.Data.Note.Types
  - Wolf.Data.NoteIndex
  - Wolf.Data.NoteIndex.Types
  - Wolf.Data.Path
  - Wolf.Data.People
  - Wolf.Data.People.Types
  - Wolf.Data.Suggestion
  - Wolf.Data.Suggestion.Types
  - Wolf.Data.Time
  - Wolf.Data.Types
