name: wolf-data
version: '0.0.0.0'
category: People
author: Tom Sydney Kerckhove
maintainer: syd.kerckhove@gmail.com
copyright: ! 'Copyright: (c) 2017 Tom Sydney Kerckhove'
license: AllRightsReserved
homepage: http://cs-syd.eu
default-extensions:
- NoImplicitPrelude
dependencies:
- base >=4.9 && <=5
- aeson >=1.0 && <1.3
- aeson-pretty >=0.8 && <0.9
- bytestring >=0.10 && <0.11
- conduit >=1.2 && <1.3
- containers >=0.5 && <0.6
- deepseq >=1.4 && <1.5
- exceptions >=0.8 && <0.9
- filepath >=1.4 && <1.5
- hashable >=1.2 && <1.3
- hashable-time >=0.2 && <0.3
- mtl >=2.2 && <2.3
- path >=0.6 && <0.7
- path-io >=1.3 && <1.4
- process >=1.6 && <1.7
- QuickCheck >=2.09 && <2.11
- resourcet >=1.1 && <1.2
- servant-server >=0.9 && <0.12
- text >=1.2 && <1.3
- time >=1.8 && <1.9
- typed-uuid >=0.0 && <0.1
- unordered-containers >=0.2 && <0.3
- uuid >=1.3 && <1.4
- validity >=0.4 && <0.5
- genvalidity >=0.4 && <0.5
- validity-aeson >=0.1 && <0.2
- validity-containers >=0.2 && <0.3
- validity-path >=0.2 && <0.3
- validity-text >=0.2 && <0.3
- validity-time >=0.1 && <0.2
- validity-uuid >=0.0 && <0.1
- yaml >=0.8 && <0.9
library:
  source-dirs: src/
  ghc-options: -Wall
  exposed-modules:
  - Wolf.Data
  - Wolf.Data.Entry
  - Wolf.Data.Entry.Types
  - Wolf.Data.Export
  - Wolf.Data.Export.Types
  - Wolf.Data.Git
  - Wolf.Data.Import
  - Wolf.Data.Import.Types
  - Wolf.Data.Index
  - Wolf.Data.Index.Types
  - Wolf.Data.Init
  - Wolf.Data.Init.Types
  - Wolf.Data.JSONUtils
  - Wolf.Data.Note
  - Wolf.Data.Note.Types
  - Wolf.Data.NoteIndex
  - Wolf.Data.NoteIndex.Types
  - Wolf.Data.Path
  - Wolf.Data.People
  - Wolf.Data.People.Types
  - Wolf.Data.Suggestion
  - Wolf.Data.Suggestion.Types
  - Wolf.Data.Time
  - Wolf.Data.Types
