name: wolf-google
version: '0.0.0.0'
category: CsSyd
author: Tom Sydney Kerckhove
maintainer: syd.kerckhove@gmail.com
copyright: ! 'Copyright: (c) 2017 Tom Sydney Kerckhove'
license: AllRightsReserved
homepage: http://cs-syd.eu
dependencies:
- base >=4.9 && <=5
library:
  source-dirs: src/
  default-extensions:
  - NoImplicitPrelude
  ghc-options: -Wall
  exposed-modules:
  - Import
  - Wolf.Google
  - Wolf.Google.OptParse
  - Wolf.Google.OptParse.Types
  - Wolf.Google.Suggest
  - Wolf.Google.Suggest.Adapt
  - Wolf.Google.Suggest.Call
  - Wolf.Google.Suggest.Finalise
  - Wolf.Google.Suggest.Gather
  - Wolf.Google.Suggest.MakeEntry
  - Wolf.Google.Suggest.Types
  dependencies:
  - aeson >=1.0
  - aeson-pretty >=0.8
  - bytestring >=0.10
  - containers >=0.5
  - exceptions >=0.8
  - gogol >=0.3
  - gogol-people >=0.3
  - http-client >=0.5
  - microlens >=0.4
  - mtl >=2.2
  - optparse-applicative >=0.13
  - process >=1.6
  - text >=1.2
  - time >=1.8
  - typed-uuid >=0.0
  - vector >=0.12
  - wolf-cli
  - wolf-data
executables:
  wolf-google:
    main: Main.hs
    source-dirs: app/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wolf-google
tests:
  wolf-google-test:
    main: Spec.hs
    source-dirs: test/
    default-extensions:
    - NoImplicitPrelude
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - wolf-google
    - hspec
