name: wolf-client
version: '0.0.0.0'
category: CsSyd
author: Tom Sydney Kerckhove
maintainer: syd.kerckhove@gmail.com
copyright: ! 'Copyright: (c) 2017 Tom Sydney Kerckhove'
license: AllRightsReserved
homepage: http://cs-syd.eu
default-extensions:
- NoImplicitPrelude
dependencies:
- base >=4.9
- servant >=0.11
- servant-client >=0.11
- text >=1.2
- wolf-api >=0.0
- wolf-data >=0.0
library:
  source-dirs: src/
  ghc-options: -Wall
  exposed-modules:
  - Wolf.Client
