name: wolf-api
version: '0.0.0.0'
category: CsSyd
author: Tom Sydney Kerckhove
maintainer: syd.kerckhove@gmail.com
copyright: ! 'Copyright: (c) 2017 Tom Sydney Kerckhove'
license: AllRightsReserved
homepage: http://cs-syd.eu
default-extensions:
- NoImplicitPrelude
dependencies:
- base >=4.9 && <=5
library:
  source-dirs: src/
  ghc-options: -Wall
  exposed-modules:
  - Wolf.API
  dependencies:
  - aeson
  - base16-bytestring >=0.1
  - bcrypt >=0.0
  - bytestring >=0.10
  - containers >=0.5
  - mtl >=2.2
  - path >=0.6
  - path-io >=1.3
  - servant >=0.11
  - text >=1.2
  - typed-uuid >=0.0
  - uuid >=1.3
  - validity >=0.4
  - validity-bytestring >=0.2
  - validity-containers >=0.2
  - validity-text >=0.2
  - validity-time >=0.1
  - wolf-data >=0.0
tests:
  wolf-api-test:
    main: Spec.hs
    source-dirs: test/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - QuickCheck
    - bytestring
    - containers
    - genvalidity
    - genvalidity-containers
    - genvalidity-hspec
    - genvalidity-hspec-aeson
    - genvalidity-text
    - genvalidity-time
    - hspec
    - http-client >=0.5
    - mtl
    - path
    - path-io
    - servant
    - text
    - wai
    - warp
    - wolf-api
    - wolf-test-utils
    - wolf-data
