name: wolf-cli
version: '0.0.0.0'
category: People
author: Tom Sydney Kerckhove
maintainer: syd.kerckhove@gmail.com
copyright: ! 'Copyright: (c) 2017 Tom Sydney Kerckhove'
license: AllRightsReserved
homepage: http://cs-syd.eu
dependencies:
- base >=4.9 && <=5
library:
  source-dirs: src/
  default-extensions:
  - NoImplicitPrelude
  ghc-options: -Wall
  exposed-modules:
  - Wolf.Cli
  - Wolf.Cli.Command.Alias
  - Wolf.Cli.Command.Entry
  - Wolf.Cli.Command.Entry.Internal
  - Wolf.Cli.Command.Export
  - Wolf.Cli.Command.Git
  - Wolf.Cli.Command.Init
  - Wolf.Cli.Command.Note
  - Wolf.Cli.Command.RandomPerson
  - Wolf.Cli.Command.Review
  - Wolf.Cli.Command.Suggestion
  - Wolf.Cli.Command.Suggestion.Internal
  - Wolf.Cli.Command.Suggestion.List
  - Wolf.Cli.Command.Suggestion.Review
  - Wolf.Cli.Command.Summary
  - Wolf.Cli.Editor
  - Wolf.Cli.OptParse
  - Wolf.Cli.OptParse.Types
  - Wolf.Cli.Prompt
  - Wolf.Cli.Report
  - Wolf.Cli.Utils
  dependencies:
  - aeson >=1.2
  - aeson-pretty >=0.8
  - ansi-terminal >=0.7
  - bytestring >=0.10
  - cautious >=0.3
  - conduit >=1.2
  - configurator >=0.3
  - containers >=0.5
  - exceptions >=0.8
  - mtl >=2.2
  - optparse-applicative >=0.14
  - path >=0.6
  - path-io >=1.3
  - process >=1.6
  - random >=1.1
  - resourcet >=1.1
  - text >=1.2
  - time >=1.8
  - typed-uuid >=0.0
  - unordered-containers >=0.2
  - uuid >=1.3
  - validity >=0.4
  - validity-containers >=0.2
  - validity-text >=0.2
  - validity-time >=0.1
  - wolf-data >=0.0
  - yaml >=0.8
executables:
  wolf:
    main: Main.hs
    source-dirs: app/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wolf-cli
tests:
  wolf-cli-test:
    main: Spec.hs
    source-dirs: test/
    default-extensions:
    - NoImplicitPrelude
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - QuickCheck
    - bytestring
    - containers
    - genvalidity
    - genvalidity-containers
    - genvalidity-hspec
    - genvalidity-hspec-aeson
    - genvalidity-text
    - genvalidity-time
    - hspec
    - mtl
    - path
    - path-io
    - text
    - uuid-types
    - wolf-cli
    - wolf-data
    - wolf-test-utils
