name: wolf-cli
version: '0.0.0.0'
category: People
author: Tom Sydney Kerckhove
maintainer: syd.kerckhove@gmail.com
copyright: ! 'Copyright: (c) 2017 Tom Sydney Kerckhove'
license: AllRightsReserved
homepage: http://cs-syd.eu
dependencies:
- base >=4.9 && <=5
library:
  source-dirs: src/
  default-extensions:
  - NoImplicitPrelude
  ghc-options: -Wall
  exposed-modules:
  - Wolf.Cli
  - Wolf.Cli.Command.Alias
  - Wolf.Cli.Command.Entry
  - Wolf.Cli.Command.Entry.Internal
  - Wolf.Cli.Command.Export
  - Wolf.Cli.Command.Git
  - Wolf.Cli.Command.Init
  - Wolf.Cli.Command.Note
  - Wolf.Cli.Command.RandomPerson
  - Wolf.Cli.Command.Review
  - Wolf.Cli.Command.Suggestion
  - Wolf.Cli.Command.Suggestion.Internal
  - Wolf.Cli.Command.Suggestion.List
  - Wolf.Cli.Command.Suggestion.Review
  - Wolf.Cli.Command.Summary
  - Wolf.Cli.Editor
  - Wolf.Cli.OptParse
  - Wolf.Cli.OptParse.Types
  - Wolf.Cli.Prompt
  - Wolf.Cli.Report
  - Wolf.Cli.Utils
  dependencies:
  - aeson >=1.2 && <1.3
  - aeson-pretty >=0.8 && <0.9
  - ansi-terminal >=0.7 && <0.8
  - bytestring >=0.10 && <0.11
  - cautious >=0.3 && <0.4
  - conduit >=1.2 && <1.3
  - configurator >=0.3 && <0.4
  - containers >=0.5 && <0.6
  - exceptions >=0.8 && <0.9
  - mtl >=2.2 && <2.3
  - optparse-applicative >=0.14 && <0.15
  - path >=0.6 && <0.7
  - path-io >=1.3 && <1.4
  - process >=1.6 && <1.7
  - random >=1.1 && <1.2
  - resourcet >=1.1 && <1.2
  - text >=1.2 && <1.3
  - time >=1.8 && <1.9
  - typed-uuid >=0.0 && <0.1
  - unordered-containers >=0.2 && <0.3
  - uuid >=1.3 && <1.4
  - validity >=0.4 && <0.5
  - validity-containers >=0.2 && <0.3
  - validity-text >=0.2 && <0.3
  - validity-time >=0.1 && <0.2
  - wolf-data >=0.0 && <0.1
  - yaml >=0.8 && <0.9
executables:
  wolf:
    main: Main.hs
    source-dirs: app/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wolf-cli
tests:
  wolf-cli-test:
    main: Spec.hs
    source-dirs: test/
    default-extensions:
    - NoImplicitPrelude
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - QuickCheck
    - bytestring
    - containers
    - genvalidity
    - genvalidity-containers
    - genvalidity-hspec
    - genvalidity-hspec-aeson
    - genvalidity-text
    - genvalidity-time
    - hspec
    - mtl
    - path
    - path-io
    - text
    - uuid-types
    - wolf-cli
    - wolf-data
    - wolf-test-utils
